import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { UserProvider } from "./_context/UserContext";
import { ServiceProvider } from "./_context/ServiceContext";
import Header from "./_components/Header";
import { StaffProvider } from "./_context/StaffContext";
import { CategoryProvider } from "./_context/CategoryContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <ServiceProvider>
            <StaffProvider>
              <CategoryProvider>
                <Header />
                {children}
                <Toaster />
              </CategoryProvider>
            </StaffProvider>
          </ServiceProvider>
        </UserProvider>
      </body>
    </html>
  );
}
